### ISSUE TITLE
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Anupam-5** [CSUBioGroup/PGMG#10]
Hi, I have built the environment successfully but when I am running the generate command the following error pops out. Please help.

(pgmg) kinshuk@kinshuk-lab:/media/kinshuk/My Book/PGMG$ python generate.py -h
Traceback (most recent call last):
  File "generate.py", line 5, in <module>
    import dgl
  File "/home/kinshuk/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from .backend import load_backend, backend_name
  File "/home/kinshuk/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/backend/__init__.py", line 109, in <module>
    load_backend(get_preferred_backend())
  File "/home/kinshuk/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/backend/__init__.py", line 43, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/home/kinshuk/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/_ffi/base.py", line 45, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/kinshuk/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/kinshuk/anaconda3/envs/pgmg/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

**Comment by e-yi** [comment]
Hi, have you solved this issue? It seems to be a fairly common problem. You might want to try following the instructions available elsewhere, like https://github.com/pyg-team/pytorch_geometric/issues/2040. That could potentially lead you to a solution. Hope this helps!

I'm closing this issue now. If you need more help, please feel free to reopen it.
