### ISSUE TITLE
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by satvikkg** [CSUBioGroup/PGMG#2]
Hi, 
   I built the environment using the environment file provided and I am getting the following error:

Traceback (most recent call last):
  File "generate.py", line 5, in <module>
    import dgl
  File "/home/administrator/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from .backend import load_backend, backend_name
  File "/home/administrator/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/backend/__init__.py", line 109, in <module>
    load_backend(get_preferred_backend())
  File "/home/administrator/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/backend/__init__.py", line 43, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/home/administrator/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/_ffi/base.py", line 45, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/administrator/anaconda3/envs/pgmg/lib/python3.8/site-packages/dgl/_ffi/base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/administrator/anaconda3/envs/pgmg/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by CSUBioGroup** [comment]
Hi, @satvikkg 

Sorry for the late reply. Please check your enviroment. The current code is tested under CUDA version 10.2. I have updated the `requirements.yml` to make it easier to install the required enviroment.

I'm closing this issue now, but please feel free to reopen it if you have further quesions.
