### ISSUE TITLE
Multiplication Error

### ISSUE THREAD

**Issue by omarnmahmood** [CSUBioGroup/PGMG#6]
Hi, I'm having trouble training a model on the provided data. I get the following error when running train_chembl_baseline.py

```
Traceback (most recent call last):
  File "PGMG/train_chembl_baseline.py", line 516, in <module>
    avg_loss = train_fn(train_loader, model, optimizer, epoch, scheduler, beta, scaler=scaler)
  File "PGMG/train_chembl_baseline.py", line 152, in train_fn
    prediction_scores, mapping_scores, lm_loss, kl_loss = model(inputs, input_mask, pp_graphs, targets)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "PGMG/model/pgmg.py", line 198, in forward
    output = self.decoder(target_embed, zzz,
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "PGMG/model/transformer_blocks.py", line 116, in forward
    x = layer(x, mem,
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/fairseq/modules/transformer_layer.py", line 641, in forward
    x, attn = self.encoder_attn(
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/fairseq/modules/multihead_attention.py", line 593, in forward
    k = self.k_proj(key)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "anaconda3/envs/pgmg/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1152x384 and 512x384)
```

**Comment by CSUBioGroup** [comment]
Hi @omarnmahmood, please first check the version of `fairseq`

**Comment by omarnmahmood** [comment]
Yes it seems that the code cannot be run on gpus that do not support cuda < 11 e.g. A100s. The issue does not appear on for example a V100

**Comment by CSUBioGroup** [comment]
The multiplication error could likely be fixed by transposing some matrices at the right spot. It seems like fairseq changed some of their behavior in versions after 10.2, which is probably what's causing the issues. Updating for more recent CUDA versions isn't on my roadmap presently. However, it shouldn't be too difficult to make it compatible.
